### ISSUE TITLE
Tileset::tiles does not contain all tiles

### ISSUE THREAD

**Issue by alexdevteam** [mapeditor/rs-tiled#103]
`Tileset::tiles` only contains tiles that have some kind of custom attribute. This makes it confusing to use since it's not mentioned in the field docs.

**Comment by alexdevteam** [comment]
I really appreciate your response, @bjorn!
Sadly, it seems this crate has been for the most part abandoned, and there are numerous issues that make it completely impossible to use (#37, #94), not mentioning its not very good interface, both to the library user and the tiled files. It's a bit disappointing that Tiled doesn't have a full rust library for interacting with the format yet. Is there an official crate planned for Rust, or are Tiled libraries all community efforts? If so, I'll continue working on a fork and contact the crate author for a possible PR.

**Comment by bjorn** [comment]
@alexdevteam At the moment I'm too unfamiliar with Rust to maintain a library myself, though I hope to become more familiar with Rust in coming months. In general there are just too many languages and frameworks, so the various loaders are all community efforts. I only officially maintain the export plugins shipping with Tiled. I hope @mattyhall will be open to share maintenance of this library and that the problems with it could be fixed.

Personally I wonder if a switch to the JSON format would be easier, for which a loader could be mostly generated. There is also https://github.com/jpgadoury01/tiled_json-rs already.

**Comment by alexdevteam** [comment]
I'd be happy to maintain this repository - I have a bit of experience from working on a crate named [dmc](https://github.com/alexdevteam/dmc) along with other binary projects, and I currently require the `tiled` crate for a project I'm working on with another person for teaching/learning purposes.
I'm currently working on a refactor: https://github.com/rusty-pizza/rs-tiled. So far I've reorganized the crate, added a few lines of documentation, added `source` to maps, and moved away the inner parse functions. It's only been two days of work but I think it's going alright.

**Comment by singalen** [comment]
This looks like the most developed crate for tiled. It's great news that it now got new maintainers and also is an official part of Tiled org!

I was a bit worried when I discovered that there's really no way to discern which Image belongs to which Tile. I'll follow @alexdevteam 's fork so far.

// I'm working on `macroquad` integration for my game. `macroquad` has its own `tiled` implementation, but it's extremely bare-bones (namely, doesn't connect with `macroquad`'s own experimental animation system).

**Comment by bjorn** [comment]
> // I'm working on `macroquad` integration for my game. `macroquad` has its own `tiled` implementation, but it's extremely bare-bones (namely, doesn't connect with `macroquad`'s own experimental animation system).

This is https://crates.io/crates/macroquad-tiled?

@not-fl3 Maybe you could share a few words about why you decided to write your own parser, as well as whether you might be interested in collaborating on this one?

**Comment by not-fl3** [comment]
TIL that tiled have animations :) 

I would assume that rs-tiled is way more feature complete, I would surely recommend using it if it does a better job! 

The main reason behind macroquad-tiled is compile time. It does not have dependencies on serde, XML, deflate and so on, while suite macroquad's quite well.

**Comment by bjorn** [comment]
> The main reason behind macroquad-tiled is compile time. It does not have dependencies on serde, XML, deflate and so on, while suite macroquad's quite well.

Is it easier to maintain a separate crate for this, rather than using features for this that could be disabled?

**Comment by not-fl3** [comment]
I am not aware of any no-dependencies tiled crates, so there is not much of a choice :)

**Comment by bjorn** [comment]
> I am not aware of any no-dependencies tiled crates, so there is not much of a choice :)

Sure. What I meant was, could `rs-tiled` be a good replacement for `macroquad-tiled`, if features like xml, deflate and serde could be disabled?

**Comment by alexdevteam** [comment]
(We don't use serde, by the way.)

**Comment by not-fl3** [comment]
Oh, my bad, I thought xml-rs use serde :)

**Comment by singalen** [comment]
I confess, I used another dependency in https://github.com/singalen/macroquad-tiled-redux: `coarsetime` ("crate to make time measurements, that focuses on speed") which in turn pulls a small bunch of dependencies. Not really necessary, but it gives me the advantage of a fast integer time arithmetics.

My approach to compilation time was to buy a faster laptop 😄

**Comment by not-fl3** [comment]
> Sure. What I meant was, could rs-tiled be a good replacement for macroquad-tiled, if features like xml, deflate and serde could be disabled?

It probably already is a replacement, to be honest. macroquad-tiled is a really small thing covering only things I found personally useful or that fitted nicely to macroquad. If one needs full-featured tiled support - some other crates would be a better choice, no doubts about that :)
