### ISSUE TITLE
Adopting this crate and moving it to mapeditor organization

### ISSUE THREAD

**Issue by bjorn** [mapeditor/rs-tiled#105]
Looking at the open pull requests, there are evidently quite a few people who would like to contribute improvements to this crate, but are unable to do so because unfortunately @mattyhall had not much time for reviews in the past months, as mentioned in https://github.com/mattyhall/rs-tiled/issues/103#issuecomment-940909303.

I would like to propose we move this create into the [mapeditor](https://github.com/mapeditor) organization, and to gather a few co-maintainers that can help with pull requests. We can set up a review policy that every change needs at least one reviewer, to help ensure the quality of the crate.

Personally I've only done a minimum amount of Rust coding, but I would be interested in helping to keep this crate up to date. I also think it would be nice if we could achieve to have "json" and "tmx" supported as features of the same crate, rather than having separate crates.

Who would be interested in helping to maintain this crate? And what do you think about this, @mattyhall?

**Comment by mattyhall** [comment]
I'd be very happy to move this crate into the mapeditor organisation

**Comment by alexdevteam** [comment]
This is great news! I'd like to help in any way possible as well, and have a few refactors I'll be pull requesting along the next coming months.

**Comment by alexdevteam** [comment]
Alright @bjorn, I got your organization invite. I am very honored to be part of it! What exactly is the plan now?

**Comment by bjorn** [comment]
> I am very honored to be part of it! What exactly is the plan now?

Right, I got distracted a bit after sending out the invite to you and @mattyhall.

So, first of all, I'm glad both of you are happy with this proposal! I'd like to find at least one additional contributor that is willing to co-maintain this package, but as far as I am concerned this is not entirely required before the next step, which would be for @mattyhall to transfer the repository into the `mapeditor` organization.

Once transferred, we should just try to pick up where things stagnated. So we'd go over the open pull requests, merge was is good and comment on what needs changes. While at it, we should ask these contributors whether they're interested in helping to maintain the package. I'd also open a Discussions section, where we could for example discuss future releases.

**Comment by mattyhall** [comment]
That should be transferred now! :smile:

**Comment by bjorn** [comment]
@mattyhall That's great news! I've already merged one of the pull requests. :partying_face: 

And, you and @alexdevteam now have maintainer permissions for this repository through the @mapeditor/rust team!

I thought GitHub had a setting to only allow merging after a review, but maybe it doesn't, at least I can't find it right now. Anyway, I would like to propose we hold off from directly pushing any changes to the repository, and instead always have at least one other member of the team review the change.

That's it for now. Don't expect a lot of activity from me the next two weeks, because it's time to take some time off for me. But let's aim for a new release soon in the next year! I hope @mattyhall will have some time to help or explain the release process by then, since at least I haven't released any crates before. :-)

**Comment by mattyhall** [comment]
The release process isn't too bad. I seem to be able to add you to an owner on crates.io, after which you should be able to run `cargo publish` from your local machine (with a clean checkout and the version number bumped) and it'll guide you through what to do. If you sign up to crates.io and give me your username I will add you :)

**Comment by alexdevteam** [comment]
Mine is `alexdevteam`, I'd be very grateful if you could add me as well. @mattyhall

**Comment by bjorn** [comment]
I'm https://crates.io/users/bjorn. I don't mind @alexdevteam to be able to push releases as well, but I would ask that we only do this with mutual agreement.

**Comment by mattyhall** [comment]
You should have both got invites not for crates.io now. I'd like to thank you both for your effort on this so far and in the future. As you can probably tell my heart hasn't particularly been in it, and my time has been limited. Seeing people take it on who really care about it and are capable of pushing it forward to be a great crate is really heartening. Hope you both had a good Christmas if you celebrate :smile:

**Comment by bjorn** [comment]
@mattyhall I hope you had a good Christmas as well, and I'd just like to take this opportunity to also thank you for building this crate and maintaining it for the past years!

**Comment by bjorn** [comment]
@PieKing1215 Somewhat related to this issue, so I'm commenting here, but would you be interested to join the team of maintainers for `rs-tiled`? You've been recently active and have already made several nice contributions, so it'd be great to have you on board!

**Comment by PieKing1215** [comment]
@bjorn Sure, I'd be interested if you think it would be helpful!

**Comment by bjorn** [comment]
@PieKing1215 Yes, the original idea was to gather several maintainers. I think it would help if we had more eyes on the Rust code (especially with me still being very new to Rust) and with our at-least-one-review policy me and @alexdevteam would be stuck if either of us is out for a while. I also hope you will continue to find time to help with further improvements. I'll send you an invite. :-)
