### ISSUE TITLE
Implement Wang tiles

### ISSUE THREAD

**Issue by singalen** [mapeditor/rs-tiled#112]
Because they are awesome.

I guess this crate: https://docs.rs/tiled-json-rs/0.2.6/tiled_json_rs/struct.WangSet.html (source repo is now deleted) can be used as a reference point.

**Comment by bjorn** [comment]
> I guess this crate: https://docs.rs/tiled-json-rs/0.2.6/tiled_json_rs/struct.WangSet.html (source repo is now deleted) can be used as a reference point.

Just note that the source just moved, see https://gitlab.com/flukejones/tiled-json-rs and [this comment](https://github.com/mapeditor/rs-tiled/issues/108#issuecomment-1000531776) by its author. But it can definitely be a good reference point.

**Comment by josebaMdeL** [comment]
HI all, I have make an initial support for WangSets, but I'm new on GitHub, and programming in general and I don't know how bad/good are my changes. There also are some things about the organization of the code that I don't understand so I wanted to know how should I proceed. Thanks in advance!

**Comment by bjorn** [comment]
@josebaMdeL Thank you so much for helping with this! To proceed, please open a pull request. You've already done so by mistake, so now would be the time to do it on purpose. :-) The pull request will be the best place where we can provide feedback on your patch and allows us to merge it.

Feel free to ask any questions on the pull request after opening it, or on Discord. We have a dedicated [#rs-tiled channel on the Tiled Discord](https://discord.gg/6pckgPJdfS).

**Comment by josebaMdeL** [comment]
Done! #226
