### ISSUE TITLE
Make TiledError non-exhaustive

### ISSUE THREAD

**Issue by alexdevteam** [mapeditor/rs-tiled#124]
That way backwards-compatibility will be preserved when adding new error types.

**Comment by bjorn** [comment]
Hmm, is this just adding `#[non_exhaustive]` before the `pub enum TiledError` and possibly also the `pub enum ParseTileError` lines? Is there anything else to keep in mind?

If it's just that I'd say we should do this for 0.10 already.

**Comment by alexdevteam** [comment]
Yes, it's just that.
