### ISSUE TITLE
Implement a proper Debug for Map / TileLayer

### ISSUE THREAD

**Issue by aleokdev** [mapeditor/rs-tiled#138]
So we don't get bombarded with this when testing:
![Screenshot_20220202_181259](https://user-images.githubusercontent.com/16354904/152203151-379f714a-c761-4cbc-a3a7-a7e474a3debd.png)

**Comment by bjorn** [comment]
Right, I guess a `LayerTileData` could debug print to something like `123:vhd`, for a tile with gid 123 that is flipped on all axis. Or did you have something else in mind?

**Comment by alexdevteam** [comment]
Whatever it is, it should be less than 1000 characters long. :p

**Comment by alexdevteam** [comment]
Maybe default debug formatting = Only show width/height, alternate = Show all tiles

**Comment by erayerdin** [comment]
Hello @aleokdev and @bjorn. Can I take this on?

**Comment by aleokdev** [comment]
Of course, feel free to! You can open a PR against `current` since this shouldn't be considered a breaking change.
