### ISSUE TITLE
Suggestion - Add different icons for Maps and Tilesets

### ISSUE THREAD

**Issue by carreraSilvio** [mapeditor/rs-tiled#165]
![image](https://user-images.githubusercontent.com/3154359/154839840-e557545b-142c-4297-b92d-66ac3274fb1b.png)

Add an icon to differentiate a map from a tileset here and hide the extensions

**Comment by alexdevteam** [comment]
You're looking for [tiled](https://github.com/mapeditor/tiled), which is the editor. This is the Rust library to interface with the TMX format.

**Comment by alexdevteam** [comment]
Also, a tip: Maps use the `tmx` extension while tilesets use the `tsx` one :)

**Comment by carreraSilvio** [comment]
Yeah, my bad! :)

**Comment by bjorn** [comment]
@alexdevteam Next time, let's just use the "Transfer issue" to move it to the right repository. :-)

**Comment by alexdevteam** [comment]
Oops, didn't know that was a thing; sorry!
