### ISSUE TITLE
`Object::id` should be required

### ISSUE THREAD

**Issue by aleokdev** [mapeditor/rs-tiled#178]
Object IDs are specified since Tiled 0.11. Our minimum supported version is 0.13, so we should require them.

**Comment by bjorn** [comment]
Even if there might be another reason why loading older files currently fails, I don't think there is a good reason to fail on missing `id` attributes rather than just defaulting them to 0 (which is an invalid ID).

**Comment by aleokdev** [comment]
> which is an invalid ID

...Where is that in the docs? 😛

**Comment by bjorn** [comment]
> ...Where is that in the docs? stuck_out_tongue

Right, there could be a mention that object IDs are always > 0, when present.
