### ISSUE TITLE
Improve Data/Wrapper docs

### ISSUE THREAD

**Issue by ShikuWorld** [mapeditor/rs-tiled#211]
Hey I was just trying to get some properties/animation/collision data from the tiles in my tileset and I found that `TileData`s visibility is `pub(crate)` so its not accessible right now and I don't see a way to do this either. There does not seem to be any plans of adding this yet.

Either we need functions to access the `TileData` properties from `Tile` or make `TileData` truely public. I don't know which approach makes more sense.

**Comment by aleokdev** [comment]
`Tile` derefs to `TileData`. You can access data from Tile directly, or if for some reason you need the data type itself (Not common) You can just `*tile`.

**Comment by ShikuWorld** [comment]
Thanks for the quick reply. Damn I tripple checked that I'm not overlooking something but dereferencing didn't even cross my mind. Tried it just now and it works. If you don't mind I would create a PR with an example showcasing this as I don't think its very obvious. Though maybe this is a very common approach and I just didn't do rust long enough yet?

**Comment by aleokdev** [comment]
I agree, the docs aren't very obvious on this regard. Perhaps adding a mention of this to the data/wrapper docs wouldn't hurt. An example showcasing the differences between the data and wrapper would be much appreciated too :)
