### ISSUE TITLE
Add way to get the LayerData from a more specific layer type like GroupLayer

### ISSUE THREAD

**Issue by lambdadeltakay** [mapeditor/rs-tiled#285]
There doesn't seem to be any way to get the name of a group layer without turning it back into a `Layer` but also it doesn't seem to be possible to do this either.

**Comment by aleokdev** [comment]
Hello, `name` is stored only in `LayerData` so if you need it you'll need it to pass it alongside `GroupLayer`.

**Comment by lambdadeltakay** [comment]
I understand
