### ISSUE TITLE
parse_with_path doesn't exist.

### ISSUE THREAD

**Issue by ghost** [mapeditor/rs-tiled#31]
`parse_with_path(Path)` doesn't exist in the current rs-tiled version.
It could be replaced with `tiled::parse_file(Path)` which worked as an alternative to `parse_with_path(Path)`.
[https://github.com/mattyhall/rs-tiled/blob/master/src/lib.rs#L371](url)

**Comment by bjorn** [comment]
I see a `parse_with_path` defined here:

https://github.com/mapeditor/rs-tiled/blob/0ca8ff1a453977fc584588bb80c7751c34cb5869/src/lib.rs#L31-L38

Should this old issue be closed?

**Comment by alexdevteam** [comment]
This is really outdated information that doesn't apply any more, so I'll close the issue.
