### ISSUE TITLE
Layering information between different types of layers can't be used

### ISSUE THREAD

**Issue by LaylBongers** [mapeditor/rs-tiled#34]
Tiled lets you layer different types of layers in whatever way you want:
![](https://i.imgur.com/HVLRfKo.png)

This is useful to for example define in what layer of a map the enemies are, so you can have tiles that are rendered above enemies. You can also have different layers of enemies (flying enemies) or effects (moving cloud, flying car entities).

This library however doesn't keep track of that information, the different layer types are sorted into their own vectors:
![](https://i.imgur.com/sACOLuf.png)

It would be better to have one single list of layers instead, with every layer entry being an enum that defines what type of layer it is, or a separate list that defines the full layering.

**Comment by bjorn** [comment]
> It would be better to have one single list of layers instead, with every layer entry being an enum that defines what type of layer it is, or a separate list that defines the full layering.

Yes, I think that'd be the best approach, but in the meantime at least #51 provided a solution for this issue.
