### ISSUE TITLE
Add a rendering example

### ISSUE THREAD

**Issue by TatriX** [mapeditor/rs-tiled#35]
It would be cool to have an opinionated rendering example. I thing piston is a good choice for this.

**Comment by TatriX** [comment]
I'll try to make one and share.

**Comment by TatriX** [comment]
Here it is.
https://github.com/TatriX/rs-tiled-piston-example

**Comment by bjorn** [comment]
@TatriX Would it be a good idea to add this example to this repository?

**Comment by TatriX** [comment]
Well, it seems piston isn't actively maintained. Perhaps `bevy` can be a better choice nowadays.

**Comment by alexdevteam** [comment]
I could do one with the `sfml` crate since that's what i'm most familiar with.

**Comment by bjorn** [comment]
> Well, it seems piston isn't actively maintained. Perhaps `bevy` can be a better choice nowadays.

Ah, alright. For `bevy` there are already [examples](https://github.com/StarArawn/bevy_tiled/tree/main/examples) in `bevy_tiled`.

> I could do one with the `sfml` crate since that's what i'm most familiar with.

Sounds like a good idea.
