### ISSUE TITLE
Vec<Vec<T>> is inefficient

### ISSUE THREAD

**Issue by moonheart08** [mapeditor/rs-tiled#54]
It would be better to index a single large Vec as a 2D object, Row Order preferably (As this is the convention used by C and most other languages)

https://stackoverflow.com/a/2151141

Why this is inefficient:
Simple, really: Heap fragmentation. This allocates one new vector for each column of the vector. I.e. in the case of `Layer`, a large layer, say, 1024x1024, will have 1025 length 1024 vectors allocated. A single vector is nicer to the kernel (One big allocation vs multiple small ones), and for iterating over the whole map, it performs quite a bit better, as the CPU can easily predict the access pattern on it's own without assistance.

**Comment by icefoxen** [comment]
Tiled's map format is kinda a pain for actually drawing stuff anyway, so if it matters I'd personally just use the `tiled` crate as a loader and copy everything into your own structure for drawing.  I had to do this anyway to get nicer tile lookups, so, probably not a big deal.
