### ISSUE TITLE
WASM external tilesets

### ISSUE THREAD

**Issue by paaaav** [mapeditor/rs-tiled#62]
Hello,

how can I use external tilesets with WASM? The file API is not implemented for the WASM target. Therefore we have to deal with URLs in the internet.

Ideally I would like an API like 
```
let map = parse_with_url(reader, Url::new("https://directory/tilemaps/")).unwrap();
```
If this is not possible I could make this work the following way
```
let tilesets = get_external_tilesets(reader).unwrap();
//request tilesets by url via Javascript, store them in my_external_tilesets, then enter WASM again
let map = parse_with_external_tilesets(reader, my_external_tilesets).unwrap();
```

Thanks

**Comment by MatthewFrench** [comment]
I also am running into this problem.

**Comment by mystal** [comment]
I had some luck with this a while back. The main issue is that this crate internally tries to open files, which does not work on WASM. So we need a way to tell it how to fetch data for external files when it's parsing. These changes tried to provide an API for doing just that:
https://github.com/mystal/rs-tiled/compare/4a456673b1a8e677534baa2e9ab59a520f9431f3..687a40133fea1dc0b23ba1588f4cf9d12b5b7d01

They're likely outdated, but could be useful to start from. They worked well enough last year for me to make a WASM build of a game running on top of [good-web-game](https://github.com/not-fl3/good-web-game).

**Comment by koalefant** [comment]
I have the same problem, just added `parse_with_file_loader` that takes a closure for file loading:
https://github.com/mattyhall/rs-tiled/pull/100

@mystal: it is a pity I haven't seen your change before implementing this.

**Comment by alexdevteam** [comment]
Keeping track of this issue in #37.
