### ISSUE TITLE
Tile ID is strange

### ISSUE THREAD

**Issue by Machine-Hum** [mapeditor/rs-tiled#68]
[tmx file](https://pastebin.com/ybTaByf2)
```
let file = File::open(&Path::new(&fname)).unwrap();
let reader = BufReader::new(file);
let mp =  parse(reader).unwrap();

info!("{:?}", mp);
```
[Output](https://pastebin.com/3m8pKKQD)

I am going to look through the code to see if I can locate the issue.

**Comment by rkanati** [comment]
Similar problem here - IDs are all as expected on `0.7`, but on `0.8` they're all either `0` or `1`. Very strange. I couldn't see anything obvious on the `git blame`, though.

**Comment by Machine-Hum** [comment]
I just switched to master and the problem went away.

**Comment by outkine** [comment]
I'm also having this issue. The IDs have little correlation to the ones that appear in `tilemap.tmx`.

**Comment by outkine** [comment]
Can confirm that master fixes this, sorry about the spam 👍
```
[dependencies]
tiled = { git = "https://github.com/mattyhall/rs-tiled" }
```

**Comment by bjorn** [comment]
Since this issue was reported fixed on `master` back in January 2020 and the current 0.9.5 release is from May 2021, I'm going to assume this can be closed. :-)
