### ISSUE TITLE
Parse layers' tint color

### ISSUE THREAD

**Issue by saintech** [mapeditor/rs-tiled#85]
It would be great if we could get [the tint color of layer](https://thorbjorn.itch.io/tiled/devlog/120663/tinting-alignment-and-object-references). This would avoid duplicating it in properties (which can cause a bugs). I can try to implement this.

**Comment by bjorn** [comment]
There has been no work on supporting tint color yet as far as I can see. Are you still interested in trying to implement this, @saintech?
