### ISSUE TITLE
Terrain data reading

### ISSUE THREAD

**Issue by josebaMdeL** [mapeditor/rs-tiled#90]
Hi!

I just needed to get this data for my game and I have added it and seems to work. I'm quite new to GitHub and I don't' know how could I send you the changes I made, if needed.

**Comment by josebaMdeL** [comment]
I have found how to do it already, forking and then making the pull request :+1:

**Comment by bjorn** [comment]
Given that terrain data has been entirely replaced by Wang Sets since Tiled 1.5, I'm closing this issue since it is essentially superseded by #112.
