### ISSUE TITLE
Add path to Tileset

### ISSUE THREAD

**Issue by AberDerBart** [mapeditor/rs-tiled#94]
I want to use multiple Maps with external tile sets. I have two issues:

- I want to manage the tilesets based on their path and avoid loading them multiple times.
- I want to resolve the location of the images used in the tileset, this is not possible, as the paths specified are relative and I don't know from the API, where the external tileset is located.

Both these issues could be solved by adding a `path` field to `Tileset`.

Also, `Image::source` would benefit from being a path that is automatically resolved while parsing.

**Comment by AberDerBart** [comment]
A workaround that works for me is making a copy of the map and embedding all tilesets:
```
tiled map.tsx --embed-tilesets --export-map map_copy.tsx
```

**Comment by toyboot4e** [comment]
I have the same issue. To clarify, `tiled::Image::source` can be either

1. relative path from `.tmx` file if the image is embedded
2. relative path from `.tsx` file

We can't know the path to an image in case 2.

---

My work around is to make relative path from `tmx` file and `tsx` to be same:

```
.
├── images
│   └── tileset_a.png
├── tmx
│   └── map_data.tsx # uses `tileset_a.tsx`
└── tsx
    └── tileset_a.tsx  # refers to `../images/tileset_a.png`
```

Then we can retrive image path like `tmx_file_path.join(tile_image.source)`.
